# Generated by Django 5.1.6 on 2026-02-24 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('icao_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('elevation_m_ft', models.CharField(max_length=30)),
                ('geoid_undulation_m', models.CharField(max_length=20)),
                ('remarks_spatial', models.TextField(blank=True, null=True)),
                ('admin_company', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_address', models.TextField(blank=True, null=True)),
                ('admin_telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_afs', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=100, null=True)),
                ('traffic_permitted', models.CharField(blank=True, max_length=50, null=True)),
                ('magnetic_variation', models.CharField(blank=True, max_length=30, null=True)),
                ('annual_change', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks_nonspatial', models.TextField(blank=True, null=True)),
                ('admin_website', models.URLField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Aerodrome',
                'verbose_name_plural': 'Aerodromes',
                'indexes': [models.Index(fields=['icao_code'], name='obstacle_co_icao_co_1aa806_idx'), models.Index(fields=['type'], name='obstacle_co_type_607be5_idx')],
                'constraints': [models.UniqueConstraint(fields=('icao_code',), name='unique_icao_code')],
            },
        ),
    ]
