# Generated by Django 5.1.6 on 2026-02-24 12:36

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerodromeBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_km', models.IntegerField()),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=20)),
                ('elevation_m_ft', models.CharField(blank=True, max_length=100)),
                ('geoid_undulation_m', models.CharField(blank=True, max_length=20)),
                ('remarks_spatial', models.TextField(blank=True)),
                ('admin_company', models.CharField(blank=True, max_length=200)),
                ('admin_address', models.TextField(blank=True)),
                ('admin_telephone', models.CharField(blank=True, max_length=100)),
                ('admin_afs', models.CharField(blank=True, max_length=20)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('traffic_permitted', models.CharField(blank=True, max_length=200)),
                ('magnetic_variation', models.CharField(blank=True, max_length=30)),
                ('annual_change', models.CharField(blank=True, max_length=30)),
                ('remarks_nonspatial', models.TextField(blank=True)),
                ('admin_website', models.URLField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('layer', models.CharField(blank=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffers', to='obstacle_compliance.aerodrome')),
            ],
            options={
                'verbose_name': 'Aerodrome Buffer',
                'verbose_name_plural': 'Aerodrome Buffers',
                'indexes': [models.Index(fields=['aerodrome', 'radius_km'], name='obstacle_co_aerodro_6f4759_idx'), django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='obstacle_co_geom_879840_gist')],
                'unique_together': {('aerodrome', 'radius_km')},
            },
        ),
    ]
