# Generated by Django 5.1.6 on 2026-02-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0002_add_aerodrome_buffer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodromebuffer',
            name='latitude_decimal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aerodromebuffer',
            name='longitude_decimal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
