# Generated by Django 5.1.6 on 2026-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0003_add_decimal_coords_and_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrome',
            name='elevation_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
