# Generated by Django 5.1.6 on 2026-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0005_populate_elevation_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrome',
            name='airlines',
            field=models.TextField(blank=True, help_text='Operating airlines', null=True),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='iata_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='nearest_city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='runway_length_m',
            field=models.FloatField(blank=True, help_text='Runway length in meters', null=True),
        ),
        migrations.AddField(
            model_name='aerodrome',
            name='source',
            field=models.CharField(choices=[('geojson', 'KCAA GeoJSON'), ('geopackage', 'OurAirports GPKG'), ('merged', 'Merged')], default='geojson', max_length=50),
        ),
    ]
