# Generated by Django 5.1.6 on 2026-07-04 11:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0006_aerodrome_airlines_aerodrome_iata_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Sunset Towers'", max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height_m', models.FloatField(help_text='Height in meters AGL')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('parcel_boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('last_status', models.CharField(choices=[('GREEN', 'Compliant'), ('YELLOW', 'Caution - Within Regulatory Zone'), ('RED', 'Hazard Detected'), ('UNKNOWN', 'Not Checked')], default='UNKNOWN', max_length=20)),
                ('last_score', models.FloatField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('status', models.CharField(choices=[('GREEN', 'Compliant'), ('YELLOW', 'Caution - Within Regulatory Zone'), ('RED', 'Hazard Detected'), ('UNKNOWN', 'Not Checked')], max_length=20)),
                ('score', models.FloatField()),
                ('primary_airport_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('airports_affected', models.IntegerField(default=0)),
                ('requires_lighting', models.BooleanField(default=False)),
                ('is_hazard', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual Check'), ('auto', 'Automatic Re-assessment'), ('bulk', 'Bulk Upload')], default='manual', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='obstacle_compliance.property')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization_type', models.CharField(choices=[('developer', 'Property Developer'), ('architect', 'Architect / Engineer'), ('agent', 'Real Estate Agent'), ('public', 'General Public'), ('kcaa', 'KCAA Regulator'), ('other', 'Other')], default='public', max_length=50)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['user', 'last_status'], name='obstacle_co_user_id_79c028_idx'),
        ),
    ]
