# Generated by Django 5.1.6 on 2026-08-11 04:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0009_notification_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerodromeRunway',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=30, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('runway_pair', models.CharField(blank=True, max_length=20, null=True)),
                ('rwy_designator_1', models.CharField(blank=True, max_length=10, null=True)),
                ('rwy_designator_2', models.CharField(blank=True, max_length=10, null=True)),
                ('thr_latitude_1_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('thr_longitude_1_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('thr_latitude_2_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('thr_longitude_2_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('thr_latitude_1', models.FloatField(blank=True, null=True)),
                ('thr_longitude_1', models.FloatField(blank=True, null=True)),
                ('thr_latitude_2', models.FloatField(blank=True, null=True)),
                ('thr_longitude_2', models.FloatField(blank=True, null=True)),
                ('thr_elevation_1_m', models.FloatField(blank=True, null=True)),
                ('thr_elevation_2_m', models.FloatField(blank=True, null=True)),
                ('thr_elevation_1_ft', models.FloatField(blank=True, null=True)),
                ('thr_elevation_2_ft', models.FloatField(blank=True, null=True)),
                ('true_bearing_1', models.CharField(blank=True, max_length=30, null=True)),
                ('true_bearing_2', models.CharField(blank=True, max_length=30, null=True)),
                ('mag_bearing_1', models.CharField(blank=True, max_length=30, null=True)),
                ('mag_bearing_2', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions_m', models.CharField(blank=True, max_length=100, null=True)),
                ('length_declared_m', models.FloatField(blank=True, null=True)),
                ('width_declared_m', models.CharField(blank=True, max_length=50, null=True)),
                ('strength_pcn_surface', models.CharField(blank=True, max_length=200, null=True)),
                ('slope_pct', models.CharField(blank=True, max_length=30, null=True)),
                ('swy_dimensions_m', models.CharField(blank=True, max_length=100, null=True)),
                ('cwy_dimensions_m', models.CharField(blank=True, max_length=100, null=True)),
                ('cwy_dimensions_m_2', models.CharField(blank=True, max_length=100, null=True)),
                ('strip_dimensions', models.CharField(blank=True, max_length=150, null=True)),
                ('strip_dimensions_m', models.CharField(blank=True, max_length=150, null=True)),
                ('ofz', models.CharField(blank=True, max_length=200, null=True)),
                ('resa_dimensions_m', models.CharField(blank=True, max_length=100, null=True)),
                ('arresting_system', models.CharField(blank=True, max_length=100, null=True)),
                ('geoid_undulation_m', models.CharField(blank=True, max_length=50, null=True)),
                ('length_calculated_m', models.FloatField(blank=True, null=True)),
                ('length_difference_m', models.FloatField(blank=True, null=True)),
                ('length_difference_pct', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Aerodrome Runway',
                'verbose_name_plural': 'Aerodrome Runways',
                'db_table': 'aerodrome-runways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeclaredDistance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=30, null=True)),
                ('runway_pair', models.CharField(blank=True, max_length=30, null=True)),
                ('rwy_designator_1', models.CharField(blank=True, max_length=10, null=True)),
                ('rwy_designator_2', models.CharField(blank=True, max_length=10, null=True)),
                ('tora_m_1', models.CharField(blank=True, max_length=20, null=True)),
                ('toda_m_1', models.CharField(blank=True, max_length=20, null=True)),
                ('asda_m_1', models.CharField(blank=True, max_length=20, null=True)),
                ('lda_m_1', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks_1', models.CharField(blank=True, max_length=300, null=True)),
                ('tora_m_2', models.CharField(blank=True, max_length=20, null=True)),
                ('toda_m_2', models.CharField(blank=True, max_length=20, null=True)),
                ('asda_m_2', models.CharField(blank=True, max_length=20, null=True)),
                ('lda_m_2', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks_2', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Declared Distance',
                'verbose_name_plural': 'Declared Distances',
                'db_table': 'runways-declared_distances',
                'managed': False,
            },
        ),
    ]
