# Generated by Django 5.1.6 on 2026-08-12 00:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle_compliance', '0011_aerodromerunway_approach_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceapplication',
            name='last_ceiling_amsl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceapplication',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceapplication',
            name='last_headroom_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceapplication',
            name='last_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceapplication',
            name='last_status',
            field=models.CharField(blank=True, choices=[('GREEN', 'Compliant'), ('YELLOW', 'Caution - Within Regulatory Zone'), ('RED', 'Hazard Detected'), ('UNKNOWN', 'Not Checked')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='UserLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('buffer', 'Buffer'), ('check_result', 'Compliance check result'), ('parcel', 'Property parcel'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'layer_type'], name='obstacle_co_user_id_52c2e1_idx')],
            },
        ),
    ]
