# Generated by Django 5.1.6 on 2025-02-10 21:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=254)),
                ("name", models.CharField(max_length=254)),
                ("iata", models.CharField(max_length=254)),
                ("icao", models.CharField(max_length=254)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("runway_len", models.BigIntegerField()),
                ("elevation_field", models.BigIntegerField()),
                ("nearest_to", models.CharField(max_length=254)),
                ("airlines", models.CharField(max_length=254)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
