# Generated by Django 5.1.6 on 2025-02-10 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airports_strips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airports",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
